const mapData = {
  level1: {
    goal: 2,
    player: { x: 6, y: 3 },
    npc: { x: 4, y: 5, movements: ['up', 'up', 'up', 'up', 'down', 'down', 'down', 'down', 'down', 'down', 'left', 'left', 'left', 'left', 'down'], currentMovementIndex: 0 },
    items: [
      { type: 'sword', x: 8, y: 2 },
    ],
    doors: [
      { type: 'dragon', x: 4, y: 9, requiredItems: ['sword'] },
      { type: 'monster', x: 8, y: 7, requiredItems: ['sword', 'potion'] },
      { type: 'princess', x: 0, y: 9, requiredItems: ['antidote'] },
    ],
    sorcerers: [
      { x: 2, y: 0, content: 'potion', revealed: false },
      { x: 4, y: 0, content: 'antidote', revealed: false },
    ],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0}, {x:8,y:0},
      {x:0,y:1}, {x:1,y:1}, {x:3,y:1}, {x:5,y:1}, {x:6,y:1}, {x:7,y:1}, {x:8,y:1},
      {x:0,y:3}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:5,y:3}, {x:7,y:3}, {x:8,y:3},
      {x:0,y:4}, {x:1,y:4}, {x:2,y:4}, {x:3,y:4}, {x:5,y:4}, {x:7,y:4}, {x:8,y:4},
      {x:0,y:5}, {x:1,y:5}, {x:2,y:5}, {x:3,y:5}, {x:5,y:5}, {x:7,y:5}, {x:8,y:5},
      {x:0,y:6}, {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6}, {x:8,y:6},
      {x:1,y:8}, {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:8,y:8},
      {x:1,y:9}, {x:2,y:9}, {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}, {x:8,y:9}
    ],
    inventory: [],
    openedDoors: []
  },
  level2: {
    goal: 2,
    player: {'x': 4, 'y': 5},
    npc: { x: 4, y: 2, movements: ["down", "right", "right", "right", "left", "left", "left", "down", "down", "down", "down", "right", "right", "right"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 3}],
    doors: [{'type': 'dragon', 'x': 8, 'y': 7, 'requiredItems': ['sword']}, {'type': 'monster', 'x': 0, 'y': 9, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 4, 'y': 9, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 0, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 8, 'y': 5, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:4,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0},,
      {x:8,y:0}, {x:0,y:2}, {x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:5,y:2}, {x:6,y:2},,
      {x:7,y:2}, {x:8,y:2}, {x:0,y:3}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:0,y:4},,
      {x:1,y:4}, {x:2,y:4}, {x:3,y:4}, {x:5,y:4}, {x:6,y:4}, {x:7,y:4}, {x:8,y:4},,
      {x:0,y:6}, {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:6,y:6}, {x:7,y:6},,
      {x:8,y:6}, {x:1,y:8}, {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8},,
      {x:8,y:8}, {x:1,y:9}, {x:2,y:9}, {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9},,
      {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level3: {
    goal: 2,
    player: {'x': 6, 'y': 3},
    npc: { x: 4, y: 5, movements: ["up", "up", "up", "up", "down", "down", "down", "down", "down", "down", "left", "left", "left", "left", "down"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 2}],
    doors: [{'type': 'monster', 'x': 8, 'y': 7, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 0, 'y': 9, 'requiredItems': ['antidote']}, {'type': 'dragon', 'x': 4, 'y': 9, 'requiredItems': ['sword']}],
    sorcerers: [{'x': 2, 'y': 0, 'content': 'potion', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 6, 'y': 0, 'content': 'sword', 'revealed': false}],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:3,y:0}, {x:5,y:0}, {x:7,y:0}, {x:8,y:0}, {x:0,y:1},,
      {x:1,y:1}, {x:3,y:1}, {x:5,y:1}, {x:7,y:1}, {x:8,y:1}, {x:0,y:3}, {x:1,y:3},,
      {x:2,y:3}, {x:3,y:3}, {x:5,y:3}, {x:7,y:3}, {x:8,y:3}, {x:0,y:4}, {x:1,y:4},,
      {x:2,y:4}, {x:3,y:4}, {x:5,y:4}, {x:7,y:4}, {x:8,y:4}, {x:0,y:5}, {x:1,y:5},,
      {x:2,y:5}, {x:3,y:5}, {x:5,y:5}, {x:7,y:5}, {x:8,y:5}, {x:0,y:6}, {x:1,y:6},,
      {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6}, {x:8,y:6}, {x:1,y:8}, {x:2,y:8},,
      {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:8,y:8}, {x:1,y:9}, {x:2,y:9},,
      {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}, {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level4: {
    goal: 2,
    player: {'x': 4, 'y': 5},
    npc: { x: 4, y: 2, movements: ["down", "right", "right", "right", "left", "left", "left", "down", "down", "down", "down", "right", "right", "right"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 3}],
    doors: [{'type': 'dragon', 'x': 8, 'y': 7, 'requiredItems': ['sword']}, {'type': 'monster', 'x': 0, 'y': 9, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 4, 'y': 9, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 0, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 0, 'y': 5, 'content': 'sword', 'revealed': false}, {'x': 8, 'y': 5, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:4,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0},,
      {x:8,y:0}, {x:0,y:2}, {x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:5,y:2}, {x:6,y:2},,
      {x:7,y:2}, {x:8,y:2}, {x:0,y:3}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:0,y:4},,
      {x:1,y:4}, {x:2,y:4}, {x:3,y:4}, {x:5,y:4}, {x:6,y:4}, {x:7,y:4}, {x:8,y:4},,
      {x:0,y:6}, {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:6,y:6}, {x:7,y:6},,
      {x:8,y:6}, {x:1,y:8}, {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8},,
      {x:8,y:8}, {x:1,y:9}, {x:2,y:9}, {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9},,
      {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level5: {
    goal: 2,
    player: {'x': 2, 'y': 2},
    npc: { x: 4, y: 7, movements: ["left", "left", "up", "up", "up", "up", "down", "right", "right", "right", "right", "down", "down", "down", "down", "down", "right"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 5}],
    doors: [{'type': 'monster', 'x': 8, 'y': 2, 'requiredItems': ['sword', 'potion']}, {'type': 'dragon', 'x': 0, 'y': 5, 'requiredItems': ['sword']}, {'type': 'princess', 'x': 8, 'y': 7, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 2, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 2, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0}, {x:8,y:0},,
      {x:0,y:1}, {x:1,y:1}, {x:3,y:1}, {x:5,y:1}, {x:6,y:1}, {x:7,y:1}, {x:8,y:1},,
      {x:0,y:3}, {x:1,y:3}, {x:3,y:3}, {x:4,y:3}, {x:5,y:3}, {x:7,y:3}, {x:8,y:3},,
      {x:0,y:4}, {x:1,y:4}, {x:3,y:4}, {x:4,y:4}, {x:5,y:4}, {x:7,y:4}, {x:8,y:4},,
      {x:5,y:5}, {x:0,y:6}, {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6},,
      {x:8,y:6}, {x:0,y:7}, {x:1,y:7}, {x:2,y:7}, {x:3,y:7}
    ],
    inventory: [],
    openedDoors: [],
  },
  level6: {
    goal: 2,
    player: {'x': 4, 'y': 7},
    npc: { x: 2, y: 2, movements: ["right", "right", "right", "right", "down", "down", "down", "right", "left", "up", "up", "up", "right"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 5}],
    doors: [{'type': 'monster', 'x': 8, 'y': 2, 'requiredItems': ['sword', 'potion']}, {'type': 'dragon', 'x': 0, 'y': 5, 'requiredItems': ['sword']}, {'type': 'princess', 'x': 8, 'y': 7, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 2, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 2, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0}, {x:8,y:0},,
      {x:0,y:1}, {x:1,y:1}, {x:3,y:1}, {x:5,y:1}, {x:6,y:1}, {x:7,y:1}, {x:8,y:1},,
      {x:0,y:3}, {x:1,y:3}, {x:3,y:3}, {x:4,y:3}, {x:5,y:3}, {x:7,y:3}, {x:8,y:3},,
      {x:0,y:4}, {x:1,y:4}, {x:3,y:4}, {x:4,y:4}, {x:5,y:4}, {x:7,y:4}, {x:8,y:4},,
      {x:5,y:5}, {x:0,y:6}, {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6},,
      {x:8,y:6}, {x:0,y:7}, {x:1,y:7}, {x:2,y:7}, {x:3,y:7}
    ],
    inventory: [],
    openedDoors: [],
  },
  level7: {
    goal: 2,
    player: {'x': 4, 'y': 7},
    npc: { x: 2, y: 2, movements: ["right", "right", "right", "right", "down", "down", "down", "right", "left", "up", "up", "up", "right"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 5}],
    doors: [{'type': 'monster', 'x': 8, 'y': 2, 'requiredItems': ['sword', 'potion']}, {'type': 'dragon', 'x': 0, 'y': 5, 'requiredItems': ['sword']}, {'type': 'princess', 'x': 8, 'y': 7, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 2, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 2, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0}, {x:8,y:0},,
      {x:0,y:1}, {x:1,y:1}, {x:3,y:1}, {x:5,y:1}, {x:6,y:1}, {x:7,y:1}, {x:8,y:1},,
      {x:0,y:3}, {x:1,y:3}, {x:3,y:3}, {x:4,y:3}, {x:5,y:3}, {x:7,y:3}, {x:8,y:3},,
      {x:0,y:4}, {x:1,y:4}, {x:3,y:4}, {x:4,y:4}, {x:5,y:4}, {x:7,y:4}, {x:8,y:4},,
      {x:5,y:5}, {x:0,y:6}, {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6},,
      {x:8,y:6}, {x:0,y:7}, {x:1,y:7}, {x:2,y:7}, {x:3,y:7}
    ],
    inventory: [],
    openedDoors: [],
  },
  level8: {
    goal: 2,
    player: {'x': 6, 'y': 2},
    npc: { x: 5, y: 7, movements: ["left", "up", "up", "left", "left", "up", "up", "up", "right", "right", "up", "down", "right", "right", "down", "down", "down", "down", "down", "right", "right", "down"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 0, 'y': 5}],
    doors: [{'type': 'monster', 'x': 8, 'y': 0, 'requiredItems': ['sword', 'potion']}, {'type': 'dragon', 'x': 0, 'y': 9, 'requiredItems': ['sword']}, {'type': 'princess', 'x': 8, 'y': 9, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 4, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 0, 'y': 2, 'content': 'sword', 'revealed': false}, {'x': 4, 'y': 9, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0},,
      {x:0,y:1}, {x:1,y:1}, {x:2,y:1}, {x:3,y:1}, {x:5,y:1}, {x:6,y:1}, {x:7,y:1},,
      {x:0,y:3}, {x:1,y:3}, {x:3,y:3}, {x:4,y:3}, {x:5,y:3}, {x:7,y:3}, {x:0,y:4},,
      {x:1,y:4}, {x:3,y:4}, {x:4,y:4}, {x:5,y:4}, {x:7,y:4}, {x:5,y:5}, {x:0,y:6},,
      {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6}, {x:8,y:6}, {x:1,y:8},,
      {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:1,y:9}, {x:2,y:9},,
      {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level9: {
    goal: 2,
    player: {'x': 5, 'y': 7},
    npc: { x: 6, y: 2, movements: ["left", "left", "up", "down", "right", "right", "down", "down", "down", "down", "down", "right", "right", "down"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 0, 'y': 5}],
    doors: [{'type': 'monster', 'x': 8, 'y': 0, 'requiredItems': ['sword', 'potion']}, {'type': 'dragon', 'x': 0, 'y': 9, 'requiredItems': ['sword']}, {'type': 'princess', 'x': 8, 'y': 9, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 4, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 0, 'y': 2, 'content': 'sword', 'revealed': false}, {'x': 4, 'y': 9, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0},,
      {x:0,y:1}, {x:1,y:1}, {x:2,y:1}, {x:3,y:1}, {x:5,y:1}, {x:6,y:1}, {x:7,y:1},,
      {x:0,y:3}, {x:1,y:3}, {x:3,y:3}, {x:4,y:3}, {x:5,y:3}, {x:7,y:3}, {x:0,y:4},,
      {x:1,y:4}, {x:3,y:4}, {x:4,y:4}, {x:5,y:4}, {x:7,y:4}, {x:5,y:5}, {x:0,y:6},,
      {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6}, {x:8,y:6}, {x:1,y:8},,
      {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:1,y:9}, {x:2,y:9},,
      {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level10: {
    goal: 2,
    player: {'x': 5, 'y': 7},
    npc: { x: 6, y: 2, movements: ["left", "left", "up", "down", "right", "right", "down", "down", "down", "down", "down", "right", "right", "down"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 0, 'y': 5}],
    doors: [{'type': 'monster', 'x': 8, 'y': 0, 'requiredItems': ['sword', 'potion']}, {'type': 'dragon', 'x': 0, 'y': 9, 'requiredItems': ['sword']}, {'type': 'princess', 'x': 8, 'y': 9, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 4, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 0, 'y': 2, 'content': 'sword', 'revealed': false}, {'x': 4, 'y': 9, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0},,
      {x:0,y:1}, {x:1,y:1}, {x:2,y:1}, {x:3,y:1}, {x:5,y:1}, {x:6,y:1}, {x:7,y:1},,
      {x:0,y:3}, {x:1,y:3}, {x:3,y:3}, {x:4,y:3}, {x:5,y:3}, {x:7,y:3}, {x:0,y:4},,
      {x:1,y:4}, {x:3,y:4}, {x:4,y:4}, {x:5,y:4}, {x:7,y:4}, {x:5,y:5}, {x:0,y:6},,
      {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6}, {x:8,y:6}, {x:1,y:8},,
      {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:1,y:9}, {x:2,y:9},,
      {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level11: {
    goal: 2,
    player: {'x': 6, 'y': 3},
    npc: { x: 4, y: 5, movements: ["up", "up", "up", "up", "down", "down", "down", "down", "down", "down", "left", "left", "left", "left", "down"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 2}],
    doors: [{'type': 'monster', 'x': 8, 'y': 7, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 0, 'y': 9, 'requiredItems': ['antidote']}, {'type': 'dragon', 'x': 4, 'y': 9, 'requiredItems': ['sword']}],
    sorcerers: [{'x': 2, 'y': 0, 'content': 'potion', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 6, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 2, 'content': 'sword', 'revealed': false}],
    blocks: [
      {x:0,y:0}, {x:1,y:0}, {x:3,y:0}, {x:5,y:0}, {x:7,y:0}, {x:8,y:0}, {x:0,y:1},,
      {x:1,y:1}, {x:3,y:1}, {x:5,y:1}, {x:7,y:1}, {x:8,y:1}, {x:0,y:3}, {x:1,y:3},,
      {x:2,y:3}, {x:3,y:3}, {x:5,y:3}, {x:7,y:3}, {x:8,y:3}, {x:0,y:4}, {x:1,y:4},,
      {x:2,y:4}, {x:3,y:4}, {x:5,y:4}, {x:7,y:4}, {x:8,y:4}, {x:0,y:5}, {x:1,y:5},,
      {x:2,y:5}, {x:3,y:5}, {x:5,y:5}, {x:7,y:5}, {x:8,y:5}, {x:0,y:6}, {x:1,y:6},,
      {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6}, {x:8,y:6}, {x:1,y:8}, {x:2,y:8},,
      {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:8,y:8}, {x:1,y:9}, {x:2,y:9},,
      {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}, {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level12: {
    goal: 2,
    player: {'x': 4, 'y': 5},
    npc: { x: 4, y: 2, movements: ["down", "right", "right", "right", "left", "left", "left", "down", "down", "down", "down", "right", "right", "right"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 3}],
    doors: [{'type': 'dragon', 'x': 8, 'y': 7, 'requiredItems': ['sword']}, {'type': 'monster', 'x': 0, 'y': 9, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 4, 'y': 9, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 0, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 8, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 5, 'content': 'sword', 'revealed': false}, {'x': 8, 'y': 5, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:4,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0},,
      {x:0,y:2}, {x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:5,y:2}, {x:6,y:2}, {x:7,y:2},,
      {x:8,y:2}, {x:0,y:3}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:0,y:4}, {x:1,y:4},,
      {x:2,y:4}, {x:3,y:4}, {x:5,y:4}, {x:6,y:4}, {x:7,y:4}, {x:8,y:4}, {x:0,y:6},,
      {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:6,y:6}, {x:7,y:6}, {x:8,y:6},,
      {x:1,y:8}, {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:8,y:8},,
      {x:1,y:9}, {x:2,y:9}, {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}, {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level13: {
    goal: 2,
    player: {'x': 6, 'y': 3},
    npc: { x: 4, y: 5, movements: ["up", "up", "up", "up", "down", "down", "down", "down", "down", "down", "left", "left", "left", "left", "down"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 2}],
    doors: [{'type': 'monster', 'x': 8, 'y': 7, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 0, 'y': 9, 'requiredItems': ['antidote']}, {'type': 'dragon', 'x': 4, 'y': 9, 'requiredItems': ['sword']}],
    sorcerers: [{'x': 0, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 2, 'y': 0, 'content': 'potion', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 6, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 4, 'content': 'sword', 'revealed': false}],
    blocks: [
      {x:1,y:0}, {x:3,y:0}, {x:5,y:0}, {x:7,y:0}, {x:8,y:0}, {x:1,y:1}, {x:3,y:1},,
      {x:5,y:1}, {x:7,y:1}, {x:8,y:1}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:5,y:3},,
      {x:7,y:3}, {x:8,y:3}, {x:1,y:4}, {x:2,y:4}, {x:3,y:4}, {x:5,y:4}, {x:7,y:4},,
      {x:8,y:4}, {x:0,y:5}, {x:1,y:5}, {x:2,y:5}, {x:3,y:5}, {x:5,y:5}, {x:7,y:5},,
      {x:8,y:5}, {x:0,y:6}, {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6},,
      {x:8,y:6}, {x:1,y:8}, {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8},,
      {x:8,y:8}, {x:1,y:9}, {x:2,y:9}, {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9},,
      {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level14: {
    goal: 2,
    player: {'x': 4, 'y': 5},
    npc: { x: 4, y: 2, movements: ["down", "right", "right", "right", "left", "left", "left", "down", "down", "down", "down", "right", "right", "right"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 3}],
    doors: [{'type': 'dragon', 'x': 8, 'y': 7, 'requiredItems': ['sword']}, {'type': 'monster', 'x': 0, 'y': 9, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 4, 'y': 9, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 0, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 8, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 5, 'content': 'sword', 'revealed': false}, {'x': 8, 'y': 5, 'content': 'potion', 'revealed': false}],
    blocks: [
      {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0}, {x:0,y:2},,
      {x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:5,y:2}, {x:6,y:2}, {x:7,y:2}, {x:8,y:2},,
      {x:0,y:3}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:0,y:4}, {x:1,y:4}, {x:2,y:4},,
      {x:3,y:4}, {x:5,y:4}, {x:6,y:4}, {x:7,y:4}, {x:8,y:4}, {x:0,y:6}, {x:1,y:6},,
      {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:6,y:6}, {x:7,y:6}, {x:8,y:6}, {x:1,y:8},,
      {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:8,y:8}, {x:1,y:9},,
      {x:2,y:9}, {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}, {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level15: {
    goal: 2,
    player: {'x': 6, 'y': 3},
    npc: { x: 4, y: 5, movements: ["up", "up", "up", "up", "down", "down", "down", "down", "down", "down", "left", "left", "left", "left", "down"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 2}],
    doors: [{'type': 'monster', 'x': 8, 'y': 7, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 0, 'y': 9, 'requiredItems': ['antidote']}, {'type': 'dragon', 'x': 4, 'y': 9, 'requiredItems': ['sword']}],
    sorcerers: [{'x': 0, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 2, 'y': 0, 'content': 'potion', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 6, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 4, 'content': 'sword', 'revealed': false}, {'x': 8, 'y': 5, 'content': 'sword', 'revealed': false}],
    blocks: [
      {x:1,y:0}, {x:3,y:0}, {x:5,y:0}, {x:7,y:0}, {x:8,y:0}, {x:1,y:1}, {x:3,y:1},,
      {x:5,y:1}, {x:7,y:1}, {x:8,y:1}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:5,y:3},,
      {x:7,y:3}, {x:8,y:3}, {x:1,y:4}, {x:2,y:4}, {x:3,y:4}, {x:5,y:4}, {x:7,y:4},,
      {x:8,y:4}, {x:0,y:5}, {x:1,y:5}, {x:2,y:5}, {x:3,y:5}, {x:5,y:5}, {x:0,y:6},,
      {x:1,y:6}, {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:7,y:6}, {x:8,y:6}, {x:1,y:8},,
      {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:7,y:8}, {x:8,y:8}, {x:1,y:9},,
      {x:2,y:9}, {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:7,y:9}, {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level16: {
    goal: 2,
    player: {'x': 4, 'y': 5},
    npc: { x: 4, y: 2, movements: ["down", "right", "right", "right", "left", "left", "left", "down", "down", "down", "down", "right", "right", "right"], currentMovementIndex: 0 },
    items: [{'type': 'sword', 'x': 8, 'y': 3}],
    doors: [{'type': 'dragon', 'x': 8, 'y': 7, 'requiredItems': ['sword']}, {'type': 'monster', 'x': 0, 'y': 9, 'requiredItems': ['sword', 'potion']}, {'type': 'princess', 'x': 4, 'y': 9, 'requiredItems': ['antidote']}],
    sorcerers: [{'x': 0, 'y': 0, 'content': 'antidote', 'revealed': false}, {'x': 4, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 8, 'y': 0, 'content': 'sword', 'revealed': false}, {'x': 0, 'y': 5, 'content': 'sword', 'revealed': false}, {'x': 8, 'y': 5, 'content': 'potion', 'revealed': false}, {'x': 7, 'y': 9, 'content': 'sword', 'revealed': false}],
    blocks: [
      {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0}, {x:0,y:2},,
      {x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:5,y:2}, {x:6,y:2}, {x:7,y:2}, {x:8,y:2},,
      {x:0,y:3}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:0,y:4}, {x:1,y:4}, {x:2,y:4},,
      {x:3,y:4}, {x:5,y:4}, {x:6,y:4}, {x:7,y:4}, {x:8,y:4}, {x:0,y:6}, {x:1,y:6},,
      {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:6,y:6}, {x:7,y:6}, {x:8,y:6}, {x:1,y:8},,
      {x:2,y:8}, {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:8,y:8}, {x:1,y:9}, {x:2,y:9},,
      {x:3,y:9}, {x:5,y:9}, {x:6,y:9}, {x:8,y:9}
    ],
    inventory: [],
    openedDoors: [],
  },
  level16: {
    goal: 2,
    player: { x: 4, y: 5 },
    npc: { x: 4, y: 2, movements: ['down', 'right', 'right', 'right', 'left', 'left', 'left', 'down', 'down', 'down', 'down', 'right', 'right', 'right'], currentMovementIndex: 0 },
    items: [
      { type: 'sword', x: 8, y: 3 },
    ],
    doors: [
      { type: 'dragon', x: 8, y: 7, requiredItems: ['sword'] },
      { type: 'monster', x: 0, y: 9, requiredItems: ['sword', 'potion'] },
      { type: 'princess', x: 4, y: 9, requiredItems: ['antidote'] },
    ],
    sorcerers: [
      { x: 0, y: 0, content: 'antidote', revealed: false },
      { x: 4, y: 0, content: 'sword', revealed: false },
      { x: 8, y: 0, content: 'sword', revealed: false },
      { x: 0, y: 5, content: 'sword', revealed: false },
      { x: 8, y: 5, content: 'potion', revealed: false },
      { x: 8, y: 9, content: 'sword', revealed: false },
    ],
    blocks: [
      {x:1,y:0}, {x:2,y:0}, {x:3,y:0}, {x:5,y:0}, {x:6,y:0}, {x:7,y:0}, {x:0,y:2},
      {x:1,y:2}, {x:2,y:2}, {x:3,y:2}, {x:5,y:2}, {x:6,y:2}, {x:7,y:2}, {x:8,y:2},
      {x:0,y:3}, {x:1,y:3}, {x:2,y:3}, {x:3,y:3}, {x:0,y:4}, {x:1,y:4}, {x:2,y:4},
      {x:3,y:4}, {x:5,y:4}, {x:6,y:4}, {x:7,y:4}, {x:8,y:4}, {x:0,y:6}, {x:1,y:6},
      {x:2,y:6}, {x:3,y:6}, {x:5,y:6}, {x:6,y:6}, {x:7,y:6}, {x:7,y:8}, {x:8,y:6}, {x:1,y:8},
      {x:3,y:8}, {x:5,y:8}, {x:6,y:8}, {x:2,y:8}, {x:1,y:9}, {x:2,y:9}, {x:3,y:9}, {x:5,y:9},
      {x:6,y:9}, {x:7,y:9}
    ],
    inventory: [],
    openedDoors: []
  },
};
export default mapData;
